package com.example.universalappnotifier.models

import com.google.gson.annotations.SerializedName

data class Value(
    @SerializedName("@odata.etag") val odataETag: String,
    val allowNewTimeProposals: Boolean,
    val attendees: List<Any>,
    val body: Body,
    val bodyPreview: String,
    @SerializedName("calendar@odata.associationLink") val calendarOdataAssociationLink: String,
    @SerializedName("calendar@odata.navigationLink") val calendarOdataNavigationLink: String,
    val categories: List<Any>,
    val changeKey: String,
    val createdDateTime: String,
    val end: End,
    val hasAttachments: Boolean,
    val hideAttendees: Boolean,
    val iCalUId: String,
    val id: String,
    val importance: String,
    val isAllDay: Boolean,
    val isCancelled: Boolean,
    val isDraft: Boolean,
    val isOnlineMeeting: Boolean,
    val isOrganizer: Boolean,
    val isReminderOn: Boolean,
    val lastModifiedDateTime: String,
    val location: Location,
    val locations: List<Any>,
    val occurrenceId: Any,
    val onlineMeeting: Any,
    val onlineMeetingProvider: String,
    val onlineMeetingUrl: Any,
    val organizer: Organizer,
    val originalEndTimeZone: String,
    val originalStartTimeZone: String,
    val recurrence: Any,
    val reminderMinutesBeforeStart: Int,
    val responseRequested: Boolean,
    val responseStatus: ResponseStatus,
    val sensitivity: String,
    val seriesMasterId: Any,
    val showAs: String,
    val start: Start,
    val subject: String,
    val transactionId: String,
    val type: String,
    val webLink: String
)